### ISSUE TITLE
no_std support?

### ISSUE THREAD

**Issue by jamesbebbington** [FloppyDisck/STEMMA_soil_moisture_sensor#3]
Thanks for creating this!

As a rust noob, slowly getting to grips with embedded systems, this is all still a bit confusing. Does the `thiserror` dependency mean that the library can't be used in a bare-metal, no_std environment? Thanks.

**Comment by FloppyDisck** [comment]
That is a very good question, my use case never thought about having no std in my crates. I will give it a look in the week to see if I can not only provide 100% support for this crate but for my other crates too.

You're also welcome to make a PR if you figure out a solution, thanks!

**Comment by jamesbebbington** [comment]
Many thanks. I have been digging into the code to see if I can make it work, but despite it all looking relatively straight-forward, I'm only very early into my journey into Rust, so am still somewhat floundering around at the moment.

**Comment by FloppyDisck** [comment]
Ill investigate into the libs, if `thiserror` is the culprit then ill look for alternative libs like `derive_more` which might have `no_std` support

**Comment by FloppyDisck** [comment]
I pushed an update, sorry it took so long

**Comment by jamesbebbington** [comment]
No worries, thanks for making the update. My Rust adventures are on pause at the moment, but I'll be sure to check it out when I pick it up again.
